name: Deploy to Cloud Run

on:
    push:
        branches:
            - main
        paths:
            - '.github/**'
            - '__tests__/**'
            - 'e2e/**'
            - 'public/**'
            - 'src/**'
            - '.docignore'
            - '.prettierrc'
            - 'Dockerfile'
            - 'eslint.config.js'
            - 'jest.config.js'
            - 'jest.setup.ts'
            - 'next.config.mjs'
            - 'package-lock.json'
            - 'package.json'
            - 'playwright.config.ts'
            - 'postcss.config.js'
            - 'tailwind.config.js'
            - 'tsconfig.json'
jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit

    deploy:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name: Authenticate Docker with GCR
              run: |
                  gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

            - name: Create file
              run: |
                  echo NEXT_PUBLIC_VISIT_ID_KEY=${{ secrets.NEXT_PUBLIC_VISIT_ID_KEY }} > .env
                  echo NEXT_PUBLIC_BACKEND_API_URL=${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }} >> .env
   

            - name: Setup Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.APP_NAME }} .
                  docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.APP_NAME }}

            - name: Deploy to Cloud Run
              run: |
                  gcloud run deploy ${{ secrets.GCP_CLOUD_RUN_SERVICE_NAME }} \
                    --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/${{ secrets.APP_NAME }} \
                    --region ${{ secrets.GCP_REGION }} \
                    --platform managed \
                    --allow-unauthenticated