name: Test Workflow

on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_dir: [
          e2e/tests/layout/*,
          e2e/tests/pages/auth/*,
          e2e/tests/pages/blog_detail/*,
          e2e/tests/pages/blog_edit_form/*,
          e2e/tests/pages/blog_home/*,
          e2e/tests/pages/blog_new_form/*,
        ]

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Create .env.test file
        run: |
          echo NEXT_PUBLIC_VISIT_ID_KEY=${{ secrets.NEXT_PUBLIC_VISIT_ID_KEY }} > .env.test
          echo NEXT_PUBLIC_BACKEND_API_URL=${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }} >> .env.test

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Playwright e2e tests
        run: npm run test:e2e -- ${{ matrix.test_dir }}

      - name: Save Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.test_dir }}
          path: playwright-report/

      - name: Remove .env.test file
        if: always()
        run: rm .env.test